### ISSUE TITLE
document known good nginx config

### ISSUE THREAD

**Issue by Shleeble** [tootsuite/flodgatt#68]
I've tried to just swap out the streaming node for flodgatt but nginx seems to have a problem accessing flodgatt with the same reverse proxy config.

I need to confirm why regular streaming works but flodgatt is broken as below.

![image](https://user-images.githubusercontent.com/17537000/71577283-88183800-2b2e-11ea-876f-e6ebe0c11fbb.png)

looks fine inside the docker container.... Can you please add additional debug information for what port is being bound.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/17537000/71577308-a2eaac80-2b2e-11ea-8eba-5763eedeaeeb.png">

**Comment by codesections** [comment]
Hmm, interesting.  I thought the issue generating the `Connection reset by peer` error message was fixed by #62.  Were you testing with the 0.3.5 release or building from Master?  I don't think the #62 fix is in the 0.3.5 release.

Either way, you are right that we should add a known-good nginx config.

**Comment by Shleeble** [comment]
That makes sense. I'm using your 0.3.5 compiled binary.

please push out a new stable and I'll try again
